/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class helloJNI */

#ifndef _Included_helloJNI
#define _Included_helloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     helloJNI
 * Method:    cal
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_helloJNI_cal
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     helloJNI
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_helloJNI_sub
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     helloJNI
 * Method:    mul
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_helloJNI_mul
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     helloJNI
 * Method:    div
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_helloJNI_div
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
